### ISSUE TITLE
App crashing w/ Field Guide

### ISSUE THREAD

**Issue by trouille** [zooniverse/mobile#267] opened 2019-07-02 01:16 UTC
The App appears to crash when you open an item within the Field Guide on Android (I haven't tested iOS). 

https://www.zooniverse.org/projects/zooniverse/floating-forests/classify
and 
https://www.zooniverse.org/projects/panthera-research/camera-catalogue/classify
and 
https://www.zooniverse.org/projects/hughdickinson/euclid-challenge-the-machines

on the app are the ones I tested with so far. Both times if I try to open the first item in their field guide, the app crashes.

**Comment by trouille** [comment] 2019-07-02 01:21
Note - this could just be my android - so good idea to check w/ other androids first before spending any significant time on this.

**Comment by eatyourgreens** [comment] 2019-07-02 06:21
The Field Guide crashes the app on my phone too: iOS 11 with limited memory. When it does open, it is very slow and unresponsive.

**Comment by chelseatroy** [comment] 2019-07-02 14:44
I am attempting to repro this now.

**Comment by trouille** [comment] 2019-07-02 14:48
My phone is an Android 7, droid turbo 2.

**Comment by chelseatroy** [comment] 2019-07-02 14:54
@trouille are you around? I'd like to verify exactly what is crashing here

**Comment by chelseatroy** [comment] 2019-07-02 15:27
OK, so I have managed to reproduce this on an OLD Android device. 

What I'm going to do now is switch to an older branch and see if this was already happening—since what we changed has nothing to do with the field guide, it would be odd for the latest version of the app to have caused this. Either way of course it needs fixing, but it may have been like this before. I'm not sure because it doesn't happen on my personal device, which is the one on which I have seen older versions of the app.

**Comment by trouille** [comment] 2019-07-03 01:11
Note - my husband also has an Android 7 - it's an LG G5. And same thing for him -- opening an item in the field guide, whether it's the floating forest field guide or the camera catalog field guide, causes it to crash the app.

**Comment by trouille** [comment] 2020-09-01 21:29
Tested on pixel3a w/ android version 10 and doesn't happen (i.e., field guide works as expected in Floating Forest w/in the app, etc.).

**Comment by trouille** [comment] 2020-09-01 21:34
Also tested on G5 android v7 and the field guide does crash the app.

**Comment by trouille** [comment] 2020-09-01 22:14
Just a note that I went through the Floating Forest field guide and resized a few images that were 1MB+ in size (and made them <60kb, so most of the ~20 images are <60kb), just to see if that was causing the issue. But the G5 Android v7 still crashes when you try to open the Floating Forest field guide. So I don't think putting a 60kb cap on field guide image file sizes is going to fix this issue.

**Comment by trouille** [comment] 2020-09-01 22:16
But also noting that Android v7 was released in 2016, so it'd be good to test with other Androids that are newer. For example, my Pixel3a w/ Android v10 doesn't crash when opening the field guide in the app (as noted above).

**Comment by trouille** [comment] 2020-09-01 22:16
@mrniaboc Do you have a non iPhone to test mobile app field guide with?

**Comment by mrniaboc** [comment] 2020-09-04 12:16
@trouille @chelseatroy I just played around with the FF field guide on the app on my Samsung Galaxy S10+ (Android 10) and it both works and looks great!

**Comment by lcjohnso** [comment] 2024-02-09 17:07
No issue persists in version 2.11; closing.

**Closed by lcjohnso** 2024-02-09 17:07 UTC
Labels: bug
