### ISSUE TITLE
bug on Android: swipe and field guide buttons expand to obscure subject

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/mobile#451] opened 2023-04-14 18:37 UTC
**What the app is supposed to do:**
- swipe and field guide buttons should not expand height to obscure subject

**What the app does instead:**
- swipe and field guide buttons height expands to obscure subject

**Exact steps to Reproduce**
0. with an Android device
1. Increase device font size
2. Click on project with swipe task, like Dark Energy Explorers
3. See how swipe and field guide buttons obscure subject

**Screenshots**
![Zooniverse_mobile_Android_issue](https://user-images.githubusercontent.com/12118751/232127759-b9c8390c-9dae-4d16-bd95-e9acf2fa946e.jpg)

**Device (please complete the following information):**
- OS: Android v11.0.11
- Device: OnePlus 10

**Additional context**
Font size increase highlights issue, though issue also noted when font size not increased
Related [Slack thread](https://zooniverse.slack.com/archives/C0K686UAW/p1681327373934729)
Related [contact ticket](https://zooniverse.freshdesk.com/a/tickets/16305)

**Comment by Saicbmm** [comment] 2024-01-13 21:00
It seems that the swipe and field guide buttons' sizes aren't constrained when the font size is increased. They need to be programmed to be within the pixel range of the suggested window. The recommended size for the Field Button (Low priority button) is 42 pixels. Its size should be somewhere around that range. This opinion is open for revisions.

**Comment by coryzoon** [comment] 2024-02-07 12:17
@mcbouslog I'm curious to know if it still looks like this for you. On my samsung with the largest font, it doesn't look ideal, but still looks better than the screenshot above.  Also curious if you have a preference for how this is fixed. I can hardcode the max height of the buttons or use a % of the screen height. Below the screenshots are 1) What it looks like on my samsung with the largest font and no code changes 2) What it looks like if I limit the height to a fixed pixel (in this example 160px) and 3) What it looks like if I limit to % of the screen height (in this example about 1/3 of the screen height). Using the percentage ensures that there is always a little bit of the image showing with the expand button so the user can expand the image to get a better look.



![Image](https://github.com/zooniverse/mobile/assets/141738821/27221107-cc4e-4fe0-b19b-c44c438f23d9)



![Image](https://github.com/zooniverse/mobile/assets/141738821/64344d11-60bb-408a-b5ca-b9f8c7a6992f)



![Image](https://github.com/zooniverse/mobile/assets/141738821/629a6684-46b9-48aa-bc9d-972feb558ebe)

**Comment by mcbouslog** [comment] 2024-02-08 18:16
I tested locally with an emulated Pixel 5 and it looks good to me as is.
<img width="485" alt="pixel5screenshot" src="https://github.com/zooniverse/mobile/assets/12118751/2fea5fe3-0132-4a90-a0b1-38f4d4b4154f">

I'm not sure if the changes that have helped mitigate this issue are released or unreleased? If released, maybe we can check with the volunteer in the linked [contact ticket](https://zooniverse.freshdesk.com/a/tickets/16305)?

I'll defer to you and @lcjohnso on how much effort to allocate to this, but I think it's looking pretty good to me as is.

**Comment by lcjohnso** [comment] 2024-02-09 16:34
I agree, current behavior seems OK so no further effort required.  Lets keep this issue open until follow-up with volunteer in original ticket is complete, but wait to follow-up until after next release (expected next week, by 16 Feb 2024) given uncertainty about what changes may have fixed behavior.

**Comment by lcjohnso** [comment] 2024-02-28 21:54
Confirmed with original reporter that everything is working as expected, so closing.  He noted that the app is "freaking gorgeous" -- nice!

cc: @mcbouslog @coryzoon

**Closed by lcjohnso** 2024-02-28 21:54 UTC
Labels: bug
